name: Build

on: [workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:2.7
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'

      - name: Install RX3-Creator
        run: |
          git clone https://github.com/pawliczka/CRX3-Creator.git /tmp/CRX3-Creator
          pip2 install -r /tmp/CRX3-Creator/requirements.txt

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build 115
        run: pnpm build

      - name: Write pem to file
        run: |
          echo "$CHROME_PEM" > /tmp/chrome.pem
        env:
          CHROME_PEM: ${{ secrets.CHROME_PEM }}

      - name: Package 115
        run: |
          python /tmp/CRX3-Creator/main.py -o 115.crx -pem /tmp/chrome.pem dist
          rm -rf release
          mv dist release
          mv 115.crx release

      - name: List release contents
        run: |
          echo "=== release contents ==="
          ls -la release || true

      - name: Upload release folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: 115-crx-release
          path: release
